### ISSUE TITLE
Repeat Function Code Not Executing

### ISSUE THREAD

**Issue by bjskistad** [bjskistad/trapjs#1]
Well, the title says it all. The repeat function in functions.js is not executing the code. I'm getting this error:
/home/ubuntu/workspace/trapcode/functions.js:25
var repeat = function(numTimes, {code}) {
                                ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.runMain [as _onTimeout] (module.js:467:10)
    at Timer.listOnTimeout (timers.js:92:15)

When I run the code. Though, the code has no errors as far as my editor can tell me.

**Comment by herohamp** [comment]
In

var repeat = function(numTimes, {code}) {
var Times = 0;
do {
code;
} while (Times < numTimes);
};

the { and } are causing an issue. I suggest you remove them

That seamed to have fixed it but now it will only execute once!

**Comment by bjskistad** [comment]
Yeah. :( Hmm... It doesn't really make sense. Should we try a for loop instead of a while loop? :/
